### PR TITLE
Dev container clean up

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78)

### CODE REVIEW

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 25 of 25 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78)* status: all files reviewed, 10 unresolved discussions (waiting on @SKairinos)

___
*[`.submodules/__main__.py` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEI5xxAwtPUruU-eT8:-NsEI5xxAwtPUruU-eT9:b-615vr3) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L13)):*
> ```Python
> present in the global-config, they will remain. However, in some cases, the
> behavior is to override the values (values not present in the global-config will
> be removed).  
> ```

Extra whitespaces
___
*[`.submodules/__main__.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEI8nk9C07luHQPbr-:-NsEI8nk9C07luHQPbr0:b22lrd7) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L15)):*
> ```Python
> be removed).  
> """
> ```

Remove line
___
*[`.submodules/__main__.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEIc0IEDh0_eMPwDHg:-NsEIc0IEDh0_eMPwDHh:b22lrd7) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L49)):*
> ```Python
> class VSCode:
>     """JSON files contained within the .vscode directory."""
> ```

Remove line
___
*[`.submodules/__main__.py` line 63 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEIczt0iys2b890MlL:-NsEIczt0iys2b890MlM:b22lrd7) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L63)):*
> ```Python
> class SubmoduleConfig:
>     """A configuration for a submodule."""
> ```

Remove line
___
*[`.submodules/__main__.py` line 96 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEJOfl9HFR458uRcEx:-NsEJOfl9HFR458uRcEy:bhfsx6m) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L96)):*
> ```Python
>     )
> 
>     return json.loads(raw_json_without_comments)
> ```

Do we need to handle the case where this "causes Python to explode" ie, if it tries to `json.loads` a jsonc file which has any of the "unauthorised" comments? I guess it would already throw an error anyway?
___
*[`.submodules/__main__.py` line 114 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEJvN4E9niYcK4hvJA:-NsEJvN4E9niYcK4hvJB:b-pm69ip) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L114)):*
> ```Python
> 
> 
> def merge_json_lists(current: JsonValue, latest: JsonList):
> ```

after our discussion in the meeting I wonder what we should settle on for these, terminology-wise.
I'm rarely a big fan of "current" and "latest" because I find they can get confusing pretty easily.

You mentioned "global" and "local" which I find a bit better, but could still be confusing, maybe?
What about "parent" and "child", or something like that, which clearly identifies which one is being inherited from and which one is extending?

Happy to discuss more.
___
*[`.submodules/__main__.py` line 390 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsERZx4Egt6YJQnmWKo:-NsERIPm41y6_jHx1MG0:b-wtrlqj) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L390)):*
> ```Python
> 
>         for inheritance in config_inheritances[::-1]:
>             inheritances.insert(index, inheritance)
> ```

What is the reason for inserting the inheritances in `inheritances` in the reverse order that they are in `config_inheritances`?
___
*[`.submodules/__main__.py` line 411 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsERbiqAxqOdnyEI-UF:-NsERbiqAxqOdnyEI-UG:b6ivrnt) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L411)):*
> ```Python
>     # Process each config.
>     for key, config in configs.items():
>         # Skip config if it's not going to merged into any submodules.
> ```

to be merged
___
*[`.vscode/settings.json` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsESW-gCNFjsL_1TEOk:-NsESW-h0oH0K_CGQ9HH:b-oe771u) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.vscode/settings.json#L17)):*
> ```JSON
>   //   "-m",
>   //   "black"
>   // ],
> ```

Remove if not needed



_Code quote:_
```JSON
  // "black-formatter.args": [
  //   "--config",
  //   "pyproject.toml"
  // ],
  // "black-formatter.path": [
  //   ".venv/bin/python",
  //   "-m",
  //   "black"
  // ],
```
___
*[`.vscode/settings.json` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsES_128bkPhSZEYVxS:-NsES_132zcIkmyQgVQ-:b-oe771u) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.vscode/settings.json#L68)):*
> ```JSON
>   //   "-c=pyproject.toml",
>   //   "."
>   // ],
> ```

Remove if not needed



_Code quote:_
```JSON
  // "isort.args": [
  //   "--settings-file=pyproject.toml"
  // ],
  // "isort.path": [
  //   ".venv/bin/python",
  //   "-m",
  //   "isort"
  // ],
  // "mypy-type-checker.args": [
  //   "--config-file=pyproject.toml"
  // ],
  // "mypy-type-checker.path": [
  //   ".venv/bin/python",
  //   "-m",
  //   "mypy"
  // ],
  // "pylint.args": [
  //   "--rcfile=pyproject.toml"
  // ],
  // "pylint.path": [
  //   ".venv/bin/python",
  //   "-m",
  //   "pylint"
  // ],
  // "python.defaultInterpreterPath": ".venv/bin/python",
  // "python.testing.pytestArgs": [
  //   "-n=auto",
  //   "-c=pyproject.toml",
  //   "."
  // ],
```

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78)* status: 23 of 30 files reviewed, 10 unresolved discussions (waiting on @faucomte97)

___
*[`.submodules/__main__.py` line 13 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEI5xxAwtPUruU-eT8:-NsIOndv8llZxzRAJoOx:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L13)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Extra whitespaces
</blockquote></details>

Done.
___
*[`.submodules/__main__.py` line 15 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEI8nk9C07luHQPbr-:-NsIOnIJERpaixhEBfeL:bx6mhim) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L15)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove line
</blockquote></details>

can't. black requires this formatting.
___
*[`.submodules/__main__.py` line 49 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEIc0IEDh0_eMPwDHg:-NsIOlWh2QbAT2dkPLwK:bx6mhim) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L49)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove line
</blockquote></details>

can't. black requires this formatting.
___
*[`.submodules/__main__.py` line 63 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEIczt0iys2b890MlL:-NsIOgXG2OK17ABGFiQU:bx6mhim) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L63)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove line
</blockquote></details>

can't. black requires this formatting.
___
*[`.submodules/__main__.py` line 96 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEJOfl9HFR458uRcEx:-NsItGgD7T4qJQ76yNfI:bupn38c) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L96)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need to handle the case where this "causes Python to explode" ie, if it tries to `json.loads` a jsonc file which has any of the "unauthorised" comments? I guess it would already throw an error anyway?
</blockquote></details>

Yes, exactly. No need for us to do anything. If there are comments still in the doc, json.loads will fail to parse the json and raise a parse error.
___
*[`.submodules/__main__.py` line 114 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsEJvN4E9niYcK4hvJA:-NsIsIUL1CXZihdqCY1H:b-swq1rq) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L114)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

after our discussion in the meeting I wonder what we should settle on for these, terminology-wise.
I'm rarely a big fan of "current" and "latest" because I find they can get confusing pretty easily.

You mentioned "global" and "local" which I find a bit better, but could still be confusing, maybe?
What about "parent" and "child", or something like that, which clearly identifies which one is being inherited from and which one is extending?

Happy to discuss more.
</blockquote></details>

change to be "global" for workspace-level-submodule-config and "submodule" for current-submodule-config.
___
*[`.submodules/__main__.py` line 390 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsERZx4Egt6YJQnmWKo:-NsItTJQC-TDv-1LcE4u:b-xjq5pp) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L390)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

What is the reason for inserting the inheritances in `inheritances` in the reverse order that they are in `config_inheritances`?
</blockquote></details>

The reason we need to insert the inheritance in reverse order is because we are inserting all the inheritances in the same index.

For example, say:

config_inheritances = [b, c, d]
index = 1
inheritances = [a, e]

then we would do:
insert d in at index 1: [a, d, e]
insert c in at index 1: [a, c, d, e]
insert b in at index 1: [a, b, c, d, e]

final result is the correct order of inheritances: [a, b, c, d, e]
___
*[`.submodules/__main__.py` line 411 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsERbiqAxqOdnyEI-UF:-NsItEgp0UHvcOweLAB0:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.submodules/__main__.py#L411)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

to be merged
</blockquote></details>

Done.
___
*[`.vscode/settings.json` line 17 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsESW-gCNFjsL_1TEOk:-NsIuMGQ8RH0FKjutR4d:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.vscode/settings.json#L17)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove if not needed
</blockquote></details>

Done.
___
*[`.vscode/settings.json` line 68 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsES_128bkPhSZEYVxS:-NsIu_Of7rB-aGBz55sg:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/8e7ab351a35f1d800e451d05956061cfa721377d/.vscode/settings.json#L68)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Remove if not needed
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 8 of 8 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`.submodules/helpers.py` line 48 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsIvTjZC5HjdC5mmgHW:-NsIvTjZC5HjdC5mmgHX:b3vx54q) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/d3b55c665e99fc32954af304f70fb71ca5bd804a/.submodules/helpers.py#L48)):*
> ```Python
> 
> 
> def merge_json_lists(current: "JsonValue", latest: "JsonList"):
> ```

still has current and latest
___
*[`.submodules/helpers.py` line 66 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsIvYc8E5EIK6Fwoi7A:-NsIvYc8E5EIK6Fwoi7B:b3vx54q) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/d3b55c665e99fc32954af304f70fb71ca5bd804a/.submodules/helpers.py#L66)):*
> ```Python
> 
> 
> def merge_json_dicts(current: "JsonValue", latest: "JsonDict"):
> ```

still has current and latest
___
*[`.submodules/helpers.py` line 101 at r2](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-NsIv_ag07mzqh6q2wBq:-NsIv_ag07mzqh6q2wBr:b3vx54q) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/d3b55c665e99fc32954af304f70fb71ca5bd804a/.submodules/helpers.py#L101)):*
> ```Python
> 
> 
> def merge_json_lists_of_json_objects(
> ```

still has current and latest

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/78#-:-NsJ6rc29SgESimfyGZQ:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
