### PR TITLE
Contributor agreement 

### PR DESCRIPTION
**Pull request by Ridwanah**
I followed the contributor agreement instructions and I added my email to the end of CONTRIBUTING.md. I accidentally committed some unnecessary files like ds_store, which you can discard.

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/127)

### CODE REVIEW

**Comment by faucomte97** [comment]
No worries @Ridwanah, you can go ahead and revert these changes yourself - the pipeline requires only `CONTRIBUTING.md` to be changed - please revert all changes other than the ones to that file.

**Comment by Ridwanah** [comment]
I reverted the other changes I made. The only change left is adding my email.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 5 files at r1, 4 of 4 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/127)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Ridwanah)

**Comment by faucomte97** [comment]
This pull request looks good @Ridwanah, we're almost there! You should have just received an email that you need to reply to with the response mentioned in the guide so we can verify you own the email. Once we receive your response, I will merge in this PR and you'll be an official Code for Life contributor!
And I will then start reviewing your other PR in rapid router 😄

**Pull request merged**
