### PR TITLE
myzabrocks@gmail.com

### PR DESCRIPTION
**Pull request by akurtle**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/71)

### CODE REVIEW

**Comment by akurtle** [comment]
Hello! I have turned the setting off, the email should be public now

**Comment by faucomte97** [comment]
Hi @akurtle, thanks for that!

I think though that because the last commit on your main branch was signed with the private email our check is still failing, so there's just one more thing you need to do, sorry!

Can you try making a very small commit, something like adding a space after your email address, and then reverting that commit, so the contents of your PR stay the same but the signature is updated? That should work.

**Comment by akurtle** [comment]
Hi, I did it right now, please let me know if thats alright!

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/71#-:-NoXMScECrJth-u1rVut:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @akurtle)

**Comment by faucomte97** [comment]
Hi @akurtle, awesome that worked!

You should have received an verification email. Please follow the instructions in that email and that should be the last step to confirming your contributor status! 🥳

**Pull request merged**
