### PR TITLE
jibran19983@gmail.com

### PR DESCRIPTION
**Pull request by Jibran1998**
Added my email address to contributors

- - -
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/109)

### CODE REVIEW

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/109#-:-Nybcuu-4Va_WGbzY4s7:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jibran1998)

**Comment by faucomte97** [comment]
Hi @Jibran1998,

Thanks! You should have received our verification email, once you reply to it as stated in step 7 then you'll officially be a contributor and I'll start reviewing your pull request on our portal repo! 🎉 🥳

**Comment by Jibran1998** [comment]
@faucomte97 Done. Thanks

**Review by faucomte97 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/109)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @Jibran1998)

**Pull request merged**
