### PR TITLE
new version email

### PR DESCRIPTION
**Pull request by SKairinos**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)

### CODE REVIEW

**Comment by SKairinos** [comment]
also need to review these email templates:
https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=1506387
https://r1-app.dotdigital.com/Campaigns/Step/EasyEditor.aspx?id=1512393

**Review by faucomte97 — APPROVED** [review]
:lgtm:

> Reviewed 6 of 6 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-:-Nnsrwj0BRQdMqrgPfj8:bnfp4nl)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)* status: all files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`CONTRIBUTING.md` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NnsyQuKCW2JMEiau4Dl:-NnsyQuKCW2JMEiau4Dm:bf2ftpq) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/1576ab83b017972c0e3e9f068e14e6e9e66046ab/CONTRIBUTING.md#L146)):*
> ```Markdown
>   branch.
> 
> 1. On the **main** branch of your forked repo, write your email address on a new
> ```

Can this specify the needs for the chevrons please

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`CONTRIBUTING.md` line 146 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NnsyQuKCW2JMEiau4Dl:-NntprUc0M03XeUOoWIf:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/1576ab83b017972c0e3e9f068e14e6e9e66046ab/CONTRIBUTING.md#L146)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Can this specify the needs for the chevrons please
</blockquote></details>

Done.

**Review by faucomte97 — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)* status: all files reviewed, 3 unresolved discussions (waiting on @SKairinos)

___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 44 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-Nntr2Jq8vU5LYCocVZn:-Nntr2Jr9zkmvb-nWqJc:b-u509h2) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L44)):*
> ```Python
>     ).stdout.decode("utf-8")
> 
>     print(previous_contributing)
> ```

Do we need this print, if it prints the whole file?
___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 109 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NntrW7-AGvuqyXve_Ks:-NntrW7049Kq5m1G_P62:b-7hb864) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L109)):*
> ```Python
>         diffs[1::2],
>     ):
>         # Only want to know which lines where removed or edited.
> ```

were*
___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 117 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NntsNSZ1hMkAmAJoW6_:-NntsNSZ1hMkAmAJoW6a:btylplx) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L117)):*
> ```Python
>                 diff_start_line_index + diff_line_index
>                 for diff_line_index, diff_line in enumerate(diff_lines)
>                 if diff_line.startswith("-")
> ```

Is this `if` needed if `diff_lines` already excludes the plusses?

**Review by SKairinos — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)* status: 5 of 6 files reviewed, 3 unresolved discussions (waiting on @faucomte97)

___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 44 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-Nntr2Jq8vU5LYCocVZn:-NnwuX3Y8ekW8JXPu80h:bqmd9lk) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L44)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Do we need this print, if it prints the whole file?
</blockquote></details>

I think it's good to have it as a sanity check. I always print the outputs of commands for debugging purposes if a workflow fails.
___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 109 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NntrW7-AGvuqyXve_Ks:-Nnwut2J6CqsGTLjDaF-:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L109)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

were*
</blockquote></details>

Done.
___
*[`.github/scripts/python/notify-new-contribution-agreement/__main__.py` line 117 at r3](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65#-NntsNSZ1hMkAmAJoW6_:-Nnwuuol2nvxBIJJ2tfY:bk8804b) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/df39b099ee38f53e916d61ca58d4ba5c029281f5/.github/scripts/python/notify-new-contribution-agreement/__main__.py#L117)):*
<details><summary><i>Previously, faucomte97 (Florian Aucomte) wrote…</i></summary><blockquote>

Is this `if` needed if `diff_lines` already excludes the plusses?
</blockquote></details>

Yes because do all some lines start with "-".  Some start with a blank space (" ") to signify no diff. For example, a git diff can look like this:

@@ -143,10 +143,9 @@ To sign, you must:
   how to do this on GitHub. Note that you only need to fork the **main**
   branch.
 
-1. On the **main** branch of your forked repo, create a new line at the *bottom*
-  of this file (press **Enter**). Note that you must not make any other edits.
-
-1. Write your email address on the second last line.
+1. On the **main** branch of your forked repo, write your email address on a new
+  line at the *bottom* of this file. Note that you must not make any other
+  edits.
 
 1. Commit your changes.

**Review by faucomte97 — APPROVED** [review]
> Reviewed 1 of 1 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/65)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @SKairinos)

**Pull request merged**
