### PR TITLE
Delete unverified users every hour

### PR DESCRIPTION
**Pull request by faucomte97**
This change is [Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5)

### CODE REVIEW

**Review by faucomte97 — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @faucomte97)

**Review by SKairinos — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5)* status: all files reviewed, 1 unresolved discussion (waiting on @faucomte97)

___
*[`cron.yaml` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5#-Ndp8T040AICh9_tlM17:-Ndp8T040AICh9_tlM18:bek66ba) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/bef485c4bb02a7ae9cabfd20b24a082bd92941ac/cron.yaml#L51)):*
> ```YAML
> 
>   - url: /cron/user/unverified/delete/
>     schedule: every hour
> ```

every 1 hours

**Review by faucomte97 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @SKairinos)

___
*[`cron.yaml` line 51 at r1](https://reviewable.io/reviews/ocadotechnology/codeforlife-workspace/5#-Ndp8T040AICh9_tlM17:-NdqyzG4Crz_fiMPpNik:b-896fix) ([raw file](https://github.com/ocadotechnology/codeforlife-workspace/blob/bef485c4bb02a7ae9cabfd20b24a082bd92941ac/cron.yaml#L51)):*
<details><summary><i>Previously, SKairinos (Stefan Kairinos) wrote…</i></summary><blockquote>

every 1 hours
</blockquote></details>

Done.

**Comment by faucomte97** [comment]
No longer needed.

**Pull request closed without merging**
